export const LED_STATE_REQUEST = "LED_STATE_REQUIRED";
export const FAN_STATE_REQUEST = "FAN_STATE_REQUIRED";
export const TEMPERATURE_STATE_REQUEST = "TEMPERATURE_STATE_REQUIRED";
export const HUMIDITY_STATE_REQUEST = "HUMIDITY_STATE_REQUIRED";
export const LIGHT_STATE_REQUEST = "LIGHT_STATE_REQUIRED";
export const HUMAN_FOUND_STATE_REQUEST = "HUMAN_FOUND_STATE_REQUIRED";

export const LED_STATE_VALID = "LED_STATE_VALID";
export const FAN_STATE_VALID = "FAN_STATE_VALID";
export const TEMPERATURE_STATE_VALID = "TEMPERATURE_STATE_VALID";
export const HUMIDITY_STATE_VALID = "HUMIDITY_STATE_VALID";
export const LIGHT_STATE_VALID = "LIGHT_STATE_VALID";
export const HUMAN_FOUND_STATE_VALID = "HUMAN_FOUND_STATE_VALID";

export const LED_STATE_INVALID = "LED_STATE_INVALID";
export const FAN_STATE_INVALID = "FAN_STATE_INVALID";
export const TEMPERATURE_STATE_INVALID = "TEMPERATURE_STATE_INVALID";
export const HUMIDITY_STATE_INVALID = "HUMIDITY_STATE_INVALID";
export const LIGHT_STATE_INVALID = "LIGHT_STATE_INVALID";
export const HUMAN_FOUND_STATE_INVALID = "HUMAN_FOUND_STATE_INVALID";

export const LED_TURN_ON = "LED_TURN_ON";
export const LED_TURN_OFF = "LED_TURN_OFF";
export const FAN_TURN_ON = "FAN_TURN_ON";
export const FAN_TURN_OFF = "FAN_TURN_OFF";
export const TEMPERATURE_TURN_ON = "TEMPERATURE_TURN_ON";
export const TEMPERATURE_TURN_OFF = "TEMPERATURE_TURN_OFF";
export const HUMIDITY_TURN_ON = "HUMIDITY_TURN_ON";
export const HUMIDITY_TURN_OFF = "HUMIDITY_TURN_OFF";
export const LIGHT_TURN_ON = "LIGHT_TURN_ON";
export const LIGHT_TURN_OFF = "LIGHT_TURN_OFF";
export const HUMAN_FOUND_TURN_ON = "HUMAN_FOUND_TURN_ON";
export const HUMAN_FOUND_TURN_OFF = "HUMAN_FOUND_TURN_OFF";

export const LED_TURN_ON_SUCCESS = "LED_TURN_ON_SUCCESS";
export const LED_TURN_OFF_SUCCESS = "LED_TURN_OFF_SUCCESS";
export const FAN_TURN_ON_SUCCESS = "FAN_TURN_ON_SUCCESS";
export const FAN_TURN_OFF_SUCCESS = "FAN_TURN_OFF_SUCCESS";
export const TEMPERATURE_TURN_ON_SUCCESS = "TEMPERATURE_TURN_ON_SUCCESS";
export const TEMPERATURE_TURN_OFF_SUCCESS = "TEMPERATURE_TURN_OFF_SUCCESS";
export const HUMIDITY_TURN_ON_SUCCESS = "HUMIDITY_TURN_ON_SUCCESS";
export const HUMIDITY_TURN_OFF_SUCCESS = "HUMIDITY_TURN_OFF_SUCCESS";
export const LIGHT_TURN_ON_SUCCESS = "LIGHT_TURN_ON_SUCCESS";
export const LIGHT_TURN_OFF_SUCCESS = "LIGHT_TURN_OFF_SUCCESS";
export const HUMAN_FOUND_TURN_ON_SUCCESS = "HUMAN_FOUND_TURN_ON_SUCCESS";
export const HUMAN_FOUND_TURN_OFF_SUCCESS = "HUMAN_FOUND_TURN_OFF_SUCCESS";

export const LED_TURN_ON_FAIL = "LED_TURN_ON_FAIL";
export const LED_TURN_OFF_FAIL = "LED_TURN_OFF_FAIL";
export const FAN_TURN_ON_FAIL = "FAN_TURN_ON_FAIL";
export const FAN_TURN_OFF_FAIL = "FAN_TURN_OFF_FAIL";
export const TEMPERATURE_TURN_ON_FAIL = "TEMPERATURE_TURN_ON_FAIL";
export const TEMPERATURE_TURN_OFF_FAIL = "TEMPERATURE_TURN_OFF_FAIL";
export const HUMIDITY_TURN_ON_FAIL = "HUMIDITY_TURN_ON_FAIL";
export const HUMIDITY_TURN_OFF_FAIL = "HUMIDITY_TURN_OFF_FAIL";
export const LIGHT_TURN_ON_FAIL = "LIGHT_TURN_ON_FAIL";
export const LIGHT_TURN_OFF_FAIL = "LIGHT_TURN_OFF_FAIL";
export const HUMAN_FOUND_TURN_ON_FAIL = "HUMAN_FOUND_TURN_ON_FAIL";
export const HUMAN_FOUND_TURN_OFF_FAIL = "HUMAN_FOUND_TURN_OFF_FAIL";

export const TEMPERATURE_STAT_REQUEST = "TEMPERATURE_STAT_REQUEST";
export const TEMPERATURE_STAT_VALID = "TEMPERATURE_STAT_VALID";
export const TEMPERATURE_STAT_INVALID = "TEMPERATURE_STAT_INVALID";

export const HUMIDITY_STAT_REQUEST = "HUMIDITY_STAT_REQUEST";
export const HUMIDITY_STAT_VALID = "HUMIDITY_STAT_VALID";
export const HUMIDITY_STAT_INVALID = "HUMIDITY_STAT_INVALID";

export const FAN_STAT_REQUEST = "FAN_STAT_REQUEST";
export const FAN_STAT_VALID = "FAN_STAT_VALID";
export const FAN_STAT_INVALID = "FAN_STAT_INVALID";

export const LIGHT_STAT_REQUEST = "LIGHT_STAT_REQUEST";
export const LIGHT_STAT_VALID = "LIGHT_STAT_VALID";
export const LIGHT_STAT_INVALID = "LIGHT_STAT_INVALID";