export const CONTEXT_LIST_REQUEST = 'CONTEXT_LIST_REQUEST'
export const CONTEXT_LIST_SUCCESS = 'CONTEXT_LIST_SUCCESS'
export const CONTEXT_LIST_FAIL = 'CONTEXT_LIST_FAIL'

export const CONTEXT_DETAIL_REQUEST = 'CONTEXT_DETAIL_REQUEST'
export const CONTEXT_DETAIL_SUCCESS = 'CONTEXT_DETAIL_SUCCESS'
export const CONTEXT_DETAIL_FAIL = 'CONTEXT_DETAIL_FAIL'

export const CONTEXT_CREATE_REQUEST = 'CONTEXT_CREATE_REQUEST'
export const CONTEXT_CREATE_SUCCESS = 'CONTEXT_CREATE_SUCCESS'
export const CONTEXT_CREATE_FAIL = 'CONTEXT_CREATE_FAIL'

export const CONTEXT_UPDATE_REQUEST = 'CONTEXT_UPDATE_REQUEST'
export const CONTEXT_UPDATE_SUCCESS = 'CONTEXT_UPDATE_SUCCESS'
export const CONTEXT_UPDATE_FAIL = 'CONTEXT_UPDATE_FAIL'

export const CONTEXT_DELETE_REQUEST = 'CONTEXT_DELETE_REQUEST'
export const CONTEXT_DELETE_SUCCESS = 'CONTEXT_DELETE_SUCCESS'
export const CONTEXT_DELETE_FAIL = 'CONTEXT_DELETE_FAIL'

export const CONTEXT_TOGGLE_REQUEST = 'CONTEXT_TOGGLE_REQUEST'
export const CONTEXT_TOGGLE_SUCCESS = 'CONTEXT_TOGGLE_SUCCESS'
export const CONTEXT_TOGGLE_FAIL = 'CONTEXT_TOGGLE_FAIL'